version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=freshcoffe
      - DB_USERNAME=root
      - DB_PASSWORD=secret
  db:
    image: mysql:5.7
    container_name: freshcoffe-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=freshcoffe
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
